//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.28 at 11:24:42 PM CET 
//


package es.uvigo.esei.testshuffler.entities;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "question", propOrder = {
    "question",
    "answers"
})
public class Question {

    @XmlElement(required = true)
    protected String question;
    @XmlElement(required = true, name = "answer")
    protected List<Answer> answers;
    @XmlAttribute(name = "complexity", required = true)
    protected Complexity complexity;
    @XmlAttribute(name = "subject", required = true)
    protected String subject;

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String value) {
        this.question = value;
    }

    public List<Answer> getAnswers() {
        if (answers == null) {
            answers = new ArrayList<Answer>();
        }
        return Collections.unmodifiableList(this.answers);
    }

    public void addAnswer(Answer answer) {
        if (answers == null) {
            answers = new ArrayList<Answer>();
        }
        this.answers.add(answer);
    }

    public Complexity getComplexity() {
        return complexity;
    }

    public void setComplexity(Complexity value) {
        this.complexity = value;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String value) {
        this.subject = value;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Question question1 = (Question) o;

        if (answers != null ? !answers.equals(question1.answers) : question1.answers != null) return false;
        if (complexity != question1.complexity) return false;
        if (question != null ? !question.equals(question1.question) : question1.question != null) return false;
        if (subject != null ? !subject.equals(question1.subject) : question1.subject != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = question != null ? question.hashCode() : 0;
        result = 31 * result + (answers != null ? answers.hashCode() : 0);
        result = 31 * result + (complexity != null ? complexity.hashCode() : 0);
        result = 31 * result + (subject != null ? subject.hashCode() : 0);
        return result;
    }
}
